# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(max)
  list,a,b = [0],0,1
  while list.last < max do
    list.push(a)
    a,b = b,a+b
  end
  list.uniq.select { |n| n <= max }
end

puts fib(4000000).select(&:even?).inject(:+)